### ISSUE TITLE
User stories: submit a poll response

### ISSUE THREAD

**Issue by ZakiaHussaini** [ZakiaHussaini/My-first-agile-project#2]
#### User story 1:
 in order to **provide my opinion with regards to a certain running topic or event** as **a user**, I can **select and submit an answer from the poll.**

#### User story 2:
 in order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response.

### Acceptance Criteria 

- Acceptance criteria 1: 
  - the option should be provided as a checkbox
  - the option should be "checked" by default
  - the option should appear next to the submit button
  - after submitting the default submission confirmation should be adjusted to include user name.

### Tasks:

- [ ] Update the view:  to poll design (HTML and CSS) to include the checkbox and to show the name of submitter
- [ ] create a new field in the model to track the username
- [ ] update the controller function
- [ ] update unit test scripts
- [ ] test the functionality

**Comment by ZakiaHussaini** [comment]
this is completed
